# NumPyによるベクトルと行列の計算

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas import Series, DataFrame

In [2]:
theta = np.pi / 3
m = np.array([[np.cos(theta),-np.sin(theta)],
              [np.sin(theta),np.cos(theta)]])
m

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

In [3]:
np.dot(m, m)

array([[-0.5      , -0.8660254],
       [ 0.8660254, -0.5      ]])

In [4]:
np.linalg.inv(m)

array([[ 0.5      ,  0.8660254],
       [-0.8660254,  0.5      ]])

In [5]:
m.T

array([[ 0.5      ,  0.8660254],
       [-0.8660254,  0.5      ]])

In [6]:
x = np.array([[1],[0]])
x

array([[1],
       [0]])

In [7]:
n = np.dot(m,x)
n

array([[ 0.5      ],
       [ 0.8660254]])

In [8]:
a = np.array([[-1],[0],[1]])
b = np.array([[2],[3],[5]])

np.dot(a.T, b)

array([[3]])

In [9]:
np.dot(a, b.T)

array([[-2, -3, -5],
       [ 0,  0,  0],
       [ 2,  3,  5]])

In [10]:
np.dot(a.T, b)[0][0]

3

In [11]:
m = np.array([[1,2],[3,4]])
m

array([[1, 2],
       [3, 4]])

In [12]:
2*m

array([[2, 4],
       [6, 8]])

In [13]:
m*2

array([[2, 4],
       [6, 8]])

In [14]:
m**2

array([[ 1,  4],
       [ 9, 16]])

In [15]:
m+10

array([[11, 12],
       [13, 14]])

In [16]:
[1,2,3] * 2

[1, 2, 3, 1, 2, 3]

In [17]:
np.array([1,2,3]) * 2

array([2, 4, 6])

In [18]:
def square(x):
    if isinstance(x, list):
        x = np.array(x)
    return x**2

In [19]:
square(3)

9

In [20]:
square([1,2,3])

array([1, 4, 9])

In [21]:
square(np.array([1,2,3]))

array([1, 4, 9])

In [22]:
def square(x):
    return x**2

square(np.array([1,2,3]))

array([1, 4, 9])

In [23]:
a = np.array([[10,20],[30,40]])
a

array([[10, 20],
       [30, 40]])

In [24]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [25]:
a+b

array([[11, 22],
       [33, 44]])

In [26]:
a-b

array([[ 9, 18],
       [27, 36]])

In [27]:
a**b

array([[     10,     400],
       [  27000, 2560000]])

In [28]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [29]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [30]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [31]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [32]:
b = a.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
c = b.reshape((3,2))
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
b.shape

(2, 3)

In [35]:
c.shape

(3, 2)

In [36]:
a = np.ones(9).reshape((3,3))
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [37]:
b = a*2
b

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [38]:
np.vstack((a,b))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [39]:
np.hstack((a,b))

array([[ 1.,  1.,  1.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  2.,  2.,  2.]])

In [40]:
x = [1,2,3,4]
np.array(x).reshape(len(x),1)

array([[1],
       [2],
       [3],
       [4]])

In [41]:
np.array([x])

array([[1, 2, 3, 4]])

In [42]:
np.array([x]).T

array([[1],
       [2],
       [3],
       [4]])

In [43]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [44]:
a = np.array([-1, 0, 1])
b = np.array([ 1, 2, 3])
np.dot(a, b)

2

In [45]:
m = np.array([1,1,1,2,2,2,3,3,3]).reshape(3,3)
m

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [46]:
np.dot(m,a)

array([0, 0, 0])

In [47]:
np.dot(a,m)

array([2, 2, 2])

## 練習問題

(1) 次の (2,2)行列 m と(2,1)行列（縦ベクトル）v をarrayオブジェクトとして定義してください。また、行列の積 w = mv を計算してください。

(2) 逆行列を計算する関数 np.linalg.inv() を利用して、次の連立方程式の解を求めてください。

(3) 次のarrayオブジェクトを「手早く」用意する方法を考えてください。

（ヒント：np.arange, reshape, T を利用します。）

(4) arrayオブジェクトを受け取って、各要素を２倍する（\*2 を演算する）関数 double を定義しなさい。また、(1)で定義した m を用いて、double(m) の結果を確認しなさい。

(5) double(m.tolist()) の結果を確認して、なぜそのような結果になったのかを考えてください。

（ヒント：tolist()メソッドは、arrayオブジェクトを通常の多次元リストに変換します。）